name: Tests

on:
  - pull_request
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.5'
      - name: Install Package and its Dependencies
        run: ./scripts/install.bash
      - name: Run tests
        run: ./scripts/test.bash
